# Generated by Django 4.2.30 on 2026-06-08 13:29

from django.db import migrations, models
import django.utils.timezone
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payment_date_paymenteditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='method',
            new_name='payment_mode',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='note',
            new_name='remarks',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_time',
            field=models.TimeField(default=payments.models.default_payment_time),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
