# Generated by Django 4.2.30 on 2026-06-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_address_customer_location_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location_lng',
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
