# Generated by Django 4.2.30 on 2026-06-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_location_lat_and_more'),
    ]

    def set_empty_location_to_null(apps, schema_editor):
        Customer = apps.get_model('customers', 'Customer')
        Customer.objects.filter(location='').update(location=None)

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
        migrations.RunPython(set_empty_location_to_null),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.location'),
        ),
    ]
