# Generated by Django 4.2.30 on 2026-06-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_location_alter_customer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='daily_collection_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekly_collection_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
