# Generated by Django 4.2.30 on 2026-06-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_latitude_customer_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='assigned_to',
            new_name='assigned_worker',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='frequency',
            new_name='collection_type',
        ),
    ]
