# Generated by Django 4.2.30 on 2026-06-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_location_options_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loan_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
